function [params_, abr]  = param_set(comp_num)

% input: the number of compartments
% return: params_set (dictionary), abr parameter (struct)

abr.ka = 400*comp_num; abr.da =2; abr.dab = 400;
abr.kb = 2*comp_num; abr.kbb = 30*comp_num;  abr.dba = 30;
abr.db = 2.8; abr.K = 0.3;
abr.kr = 0.1*comp_num; abr.krb = 1.5*comp_num; abr.dr = 0.2;

key_vals = {'comp_num', 'motor_amount',...
    'diffco', 'diffco_im', 'diffco_am', ...
    'diffco_bm', 'v_am', 'dragco', ...
    'kactive_motor', 'kdeactive_motor', ...
    'kbind', 'kunbind', 'kreversal', ...
    'shifttime', 'shiftduration', 'shiftmag'
    };

val_Set = [comp_num, 1, ...
    1000, 200, 20,...
    0.1, 60, 100,...
    60, 1000, ...
    75, 30, 60, ...
    -1, 3, 1];

params_ = containers.Map(key_vals,val_Set);